spring.datasource.url=jdbc:postgresql://localhost:5432/pathwise
spring.datasource.username=postgres
spring.datasource.password=sidharth
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a92f036787352319ce9287391b1df404
jwt.expiration=86400000

# Google OAuth Configuration
google.client.id=210398161723-ndaehvdjiuml1v4tu11ee3ut1235d5kk.apps.googleusercontent.com
